### ISSUE TITLE
Conflict between the custom add to cart icon and woocommerce default checkmark icon after adding to cart

### ISSUE THREAD

**Issue by sabbirahasanhabib** [UraraReika/jet-woo-builder-custom-add-to-cart-icon#2]
Hello there,
I am having an issue with the custom add to cart icon..It messes up with the default checkmark icon after a product has been added to cart. Please check the images..can you plz check the code of this plugin?
![Screenshot_4](https://github.com/UraraReika/jet-woo-builder-custom-add-to-cart-icon/assets/137334915/af0bdf27-db8d-4404-85e8-455b938dec3d)
![Screenshot_5](https://github.com/UraraReika/jet-woo-builder-custom-add-to-cart-icon/assets/137334915/94c3c524-a33b-42d4-9819-d98aeeda7b72)

**Comment by sabbirahasanhabib** [comment]
@UraraReika

**Comment by UraraReika** [comment]
Will check and fix this issue soon

**Comment by sabbirahasanhabib** [comment]
Thanks a lot❤️❤️❤️.. It will be a life saving

**Comment by UraraReika** [comment]
Fix available on git

**Comment by sabbirahasanhabib** [comment]
Awesome Buddy ...I didn't expect the issue will be solved such a quick way...you are genius...crocoblock is great :)

**Comment by sabbirahasanhabib** [comment]
@UraraReika Sorry for posting here again...The add to cart icon is working perfectly in the single product page that u have solved 3 weeks ago...but the issue persists in the shop page..plz checkout the screenshots

This is the single product page
![Screenshot_13](https://github.com/UraraReika/jet-woo-builder-custom-add-to-cart-icon/assets/137334915/eb4cc492-db71-4d8a-83c1-270e7faa0502)

this is the shop page
![Screenshot_14](https://github.com/UraraReika/jet-woo-builder-custom-add-to-cart-icon/assets/137334915/e2bba80d-cd5f-4bce-9dfb-8b6640af2571)

It would be great if you fix this soon buddy...Thanks a lot for the previous help again :)

**Comment by sabbirahasanhabib** [comment]
@UraraReika Can you plz check it from your end?

**Comment by UraraReika** [comment]
Feel free to download the latest version from git.

**Comment by sabbirahasanhabib** [comment]
Awesome..The problem has been fixed....I can understand your situation..A lot of people are banging your head over different issues...Thanks a lot again.
